### ISSUE TITLE
Include enum values in type definition

### ISSUE THREAD

**Issue by guidoren** [andry-tino/Rosetta#23]
The definition runner exports enum type names, but the enum values are not included.

Example:
```
enum Status {
    Inactive = 0,
    Active = 1
};
```

**expected type definition:**
```
declare enum Status {
    Inactive = 0,
    Active = 1,
}
```

**actual type definition:**
```
declare enum Status {
 } 
```

**Comment by andry-tino** [comment]
This will be treated as a **MUST** and will be implemented soon.
