### ISSUE TITLE
Type definitions for setters are missing return type

### ISSUE THREAD

**Issue by guidoren** [andry-tino/Rosetta#25]
Setters are emitted as:

    set_example(value : Example);

If `implicit allow any` is enabled that will compile fine; otherwise it is a compile error.
Instead, this should be emitted:

    set_example(value : Example): void;

**Comment by andry-tino** [comment]
Will always emit the return type in order to fix this. \

### Scope
This feature will only be available in the ScriptSharp definition generator as we want to introduce a flag in the normal transpiler for emitting `void` and `any` explicitely or not (same as `implicit allow any`)
