### ISSUE TITLE
DefinitionRunner throws error on static field declarations

### ISSUE THREAD

**Issue by guidoren** [andry-tino/Rosetta#26]
A declaration like:

    static int example = 42;

throws an error `("An error occurred: Not recognized visibility!!")` when executing the definition runner.

**Comment by andry-tino** [comment]
The error message is unfortunately misleading as actually the problem is handling static members. A new issue will be created to track this enhancement. When ready this bug will be closed and referenced to that issue,

**Comment by andry-tino** [comment]
This will be covered by #28.
