### ISSUE TITLE
Honor ScriptName attribute

### ISSUE THREAD

**Issue by janis-veinbergs** [andry-tino/Rosetta#58]
Once upon a time [PreserveCase/PreserveName rolled into ScriptName attribute] for ScriptSharp. (https://github.com/nikhilk/scriptsharp/commit/7abd05cf1dbefe6eaf3cb271f7fedec54cc9c4e7)

PR incoming to honor this tag.

Is this project dead or PRs still welcome @andry-tino?

**Comment by andry-tino** [comment]
Hi @janis-veinbergs  and thanks for writing.This project is kind of dead unfortunately and I will update the README to reflect that.

Please consider forking it to adapt the code to your needs.

Also consider that, at the time of my last change, a comprehensive set of tests has been introduced. Consider running them all to make sure your changes did not regress anything.

Have a nice day.

**Comment by janis-veinbergs** [comment]
Okay.

Yes, I did run tests and did add bunch more to test implemented functionality. 

Anyways, thanks for project - provides a great starting point for typescript definitions from scriptsharp project.

**Comment by andry-tino** [comment]
@janis-veinbergs thank YOU for spending time creating the PR and sorry for not clarifying in the README that this project is not moving forward.

The reason for me keeping it here is twofold:

- Allowing others to build on top of it
- Hoping, in future, to be able to get back at it

I hope this can be useful to you. I wish you the best of luck on your efforts!
